@extends('layouts.backend.layouts.app')
@section('content')
    <div class="container-fluid">
      <div class="row">
        {{-- <div class="col-md-8"> --}}
          <div class="card">
            {{-- @include('layouts.backend.invoice.menu') --}}
            <div class="card-body">
                {{-- <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".create">Generate Invoice</button> --}}
                {{-- <a class="btn btn-primary pull-right" href="{{route('generate.invoices')}}">
                    Generate Invoice
                </a> --}}
                <div class="clearfix"></div>
                <br>
                @php
                 $i = 1;
                @endphp
                <table class="table table-bordered" class="table-hover" id="get-admin-invoice"  width="100%">
                    <thead>
                    <tr style="text-align: center">
                        <th scope="col">SL</th>
                        <th scope="col">Date</th>
                        <th scope="col">Invoice ID</th>
                        <th scope="col">Merchant</th>
                        <th scope="col">Mobile</th>
                        <th scope="col">Total Deliveries</th>
                        <th scope="col">Total Payout</th>
                        @if(auth()->user()->role_id == 1 || auth()->user()->role_id == 2)
                        <th scope="col">Generated By</th>
                        @endif
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


    <div class="modal fade delete" tabindex="-1" role="dialog" id="confirm" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <p>Are you sure you want to delete this?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Delete</button>
                    <a href=""></a>
                    <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


@endsection

@push('scripts')
    <script>
        $(function() {
            $('#get-admin-invoice').DataTable({
                processing: true,
                serverSide: true,
                // responsive: true,
                scrollX: true,
                scrollY: "500px",
                // paging: false,
                ajax: '{{ url('get-invoices') }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'id', orderable: false },
                    { data: 'date', name: 'date', orderable: false },
                    { data: 'invoice_id', name: 'invoice_id', orderable: false },
                    { data: 'merchant', name: 'merchant', orderable: false },
                    { data: 'mobile', name: 'mobile', orderable: false },
                    { data: 'total_deliveries', name: 'total_deliveries', orderable: false },
                    { data: 'total_payout', name: 'total_payout', orderable: false },
                    @if(auth()->user()->role_id == 1 || auth()->user()->role_id == 2)
                    { data: 'creator', name: 'creator', orderable: false },
                    @endif
                    { data: 'action', name: 'action', orderable: false,
                        render:
                            function(data, type, row) {
                                    if(data == 1){
                                        return '<div style="text-align:center" class="action-btn">'+
                                            '<a id="confirm" class="btn btn-primary btn-sm" title="Delete" href="/invoice/'+row.id+'">View</a>'+
                                            '<a id="confirm" class="btn btn-danger btn-sm delete" title="Delete" href="/invoice/delete/'+row.id+'">Delete</a>'+
                                        '</div>';
                                    }else if(data == 3){
                                        return '<div style="text-align:center" class="action-btn">'+
                                            '<a id="confirm" class="btn btn-primary btn-sm" title="Delete" href="/invoice/'+row.id+'">View</a>'+
                                            '</div>';
                                    }else{
                                        return '<div style="text-align:center" class="action-btn">'+
                                            '<a id="confirm" class="btn btn-primary btn-sm" title="Delete" href="/invoice/'+row.id+'">View</a>'+
                                        '</div>';
                                    }
                            }
                    },
                ],

            });

        });

    </script>
@endpush
